language: go

sudo: false

install: true

go:
  - 1.11.x

env:
  - GO111MODULE=on

notifications:
  email: false

before_script:
# - go install -mod vendor github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - go build
# - golangci-lint run
  - go test ./...
  - go test ./... -bench .
